### ISSUE TITLE
Difference between screen and modal.

### ISSUE THREAD

**Issue by whynames** [Zitga-Tech/ZBase.UnityScreenNavigator#1]
Hey, Screens and modals have very similar functionality, but in my tests a screen loads in around 150ms, but modal loads in 0.5ms. Why it might be? Am I doing something wrong or is it expected?

**Comment by grashaar** [comment]
Hi! I'm very sorry for the late response.

I've done a simple test using the existing demo. There is no perceptible difference between scene and modal loading for the first time. On my machine, both of them take 100ms. The demo also has pooling enabled, so the second time a modal is loaded it will take near to 0ms.

If you were using the latest version at that time (1.5.13), loading mechanism has already been unified. You can always put a test on the method `GetViewAsync<T>` inside `ViewContainerBase`.
