### ISSUE TITLE
The transition effect is not seamless between the two screens

### ISSUE THREAD

**Issue by huynhthuan** [Zitga-Tech/ZBase.UnityScreenNavigator#2]
![image](https://github.com/Zitga-Tech/ZBase.UnityScreenNavigator/assets/43500546/1c70f77c-a6c4-48aa-bd77-2ca98a48246a)

When I switch between two screen, the animation is not seamless and there is black space in between the two screen.

Demo: https://github.com/huynhthuan/unityNavigatorDemo

**Comment by grashaar** [comment]
Thanks for reporting this.
Fixed in version `1.6.5`
